"🔧 library":
  - changed-files:
      - any-glob-to-any-file:
          - src/**

"⌨️ cli":
  - changed-files:
      - any-glob-to-any-file:
          - bin/**

"🧪 tests":
  - changed-files:
      - any-glob-to-any-file:
          - test/**

"📄 docs":
  - changed-files:
      - any-glob-to-any-file:
          - "README*.md"
          - CONTRIBUTING.md
          - CODE_OF_CONDUCT.md
          - SECURITY.md
          - NOTICE

"📦 dependencies":
  - changed-files:
      - any-glob-to-any-file:
          - package.json
          - package-lock.json

"⚙️ ci":
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
